// This file is fully generated by running parsergen
// with grammer definition file grammar.txt
// Read ParserGen.chm for further info.

#ifndef ParserH
#define ParserH

#include <bux/LR1.h>

// %PRECLASSDECL expanded BEGIN
extern int errors;
// %PRECLASSDECL expanded END

class C_CalcParser: public bux::LR1::C_Parser
{
public:

    // Ctor
    C_CalcParser();
};

#endif // ParserH
