// This file is fully generated by running parsergen v1.7.5
// with grammer definition file "grammar.txt"

#pragma once

#include <bux/LexBase.h>    // bux::TOKENGEN_LB

// Token Id Constants
enum
{
    TID_LEX_Num     = bux::TOKENGEN_LB+0,	// $Num
    TID_LEX_Spaces  = bux::TOKENGEN_LB+1,	// $Spaces
    TID_UB_
};
