// This file is fully generated by running parsergen
// with grammer definition file grammar.txt
// Read ParserGen.chm for further info.

#ifndef ParserIdDef_H
#define ParserIdDef_H

#include <bux/LexBase.h>    // bux::TOKENGEN_LB

// Token Id Constants
enum
{
    TID_LEX_Num     = bux::TOKENGEN_LB+0,	// $Num
    TID_LEX_Spaces  = bux::TOKENGEN_LB+1,	// $Spaces
    TID_UB_
};

#endif // ParserIdDef_H
