// This file is fully generated by running parsergen v1.6.3
// with grammer definition file "grammar.txt"

#ifndef ParserH
#define ParserH

#include <bux/LR1.h>

class C_Parser: public bux::LR1::C_Parser
{
public:

    // Data
    std::ostream &          m_context;

    // Ctor
    template<class...T_Args>
    C_Parser(T_Args&&...args): bux::LR1::C_Parser(policy()), m_context(std::forward<T_Args>(args)...) {}

private:

    static const bux::LR1::I_ParserPolicy &policy();
};

#endif // ParserH
