// This file is fully generated by running parsergen
// with grammer definition file grammar.txt
// Read ParserGen.chm for further info.

#ifndef ParserH
#define ParserH

#include "GLR.h"

// %PRECLASSDECL expanded BEGIN
extern int errors;
// %PRECLASSDECL expanded END

class C_GLRPOC: public bux::GLR::C_Parser
{
public:

    // Ctor
    C_GLRPOC();
};

#endif // ParserH
