// This file is fully generated by running parsergen v1.7.0
// with grammer definition file "grammar.txt"

#pragma once

#include <bux/GLR.h>
// Grammar %HEADERS_FOR_HEADER undefined (expanded here otherwise)
// Grammar %PRECLASSDECL undefined (expanded here otherwise)

class C_Parser: public bux::GLR::C_Parser
{
public:

    // Type
    using C_Context = std::remove_reference_t<std::ostream>;

    // Ctor
    C_Parser(C_Context &context): C_Parser() { userData(&context); }

private:

    C_Parser();
// Grammar %INCLASSDECL undefined (expanded here otherwise)
};
