// This file is fully generated by running parsergen v1.7.1
// with grammer definition file "grammar.txt"

#pragma once

#include <bux/LexBase.h>    // bux::TOKENGEN_LB

// Token Id Constants
enum
{
    TID_LEX_Id          = bux::TOKENGEN_LB+0,	// $Id
    TID_LEX_Spaces      = bux::TOKENGEN_LB+1,	// $Spaces
    TID_KEYWORD_type    = bux::TOKENGEN_LB+2,	// "type"
    TID_LITERAL_2e2e    = bux::TOKENGEN_LB+3,	// ".."
    TID_UB_
};
