// This file is fully generated by running parsergen v1.6.3
// with grammer definition file "grammar.txt"

#ifndef ParserH
#define ParserH

#include <bux/GLR.h>

class C_Parser: public bux::GLR::C_Parser
{
public:

    // Type
    using C_Context = std::remove_reference_t<std::ostream>;

    // Ctor
    C_Parser(C_Context &context): C_Parser() { userData(&context); }

private:

    C_Parser();
};

#endif // ParserH
