// This file is fully generated by running parsergen v1.6.0
// with grammer definition file "grammar.txt"

#ifndef ParserIdDef_H
#define ParserIdDef_H

#include <bux/LexBase.h>    // bux::TOKENGEN_LB

// Token Id Constants
enum
{
    TOKENGEN_UB = bux::TOKENGEN_LB
};

#endif // ParserIdDef_H
