// This file is fully generated by running parsergen
// with grammer definition file grammar.txt
// Read ParserGen.chm for further info.

#ifndef ParserH
#define ParserH

#include "LR1.h"

class C_MinParser: public bux::LR1::C_Parser
{
public:

    // Ctor
    C_MinParser();
};

#endif // ParserH
