// This file is fully generated by running parsergen v1.6.2
// with grammer definition file "grammar.txt"

#ifndef ParserH
#define ParserH

#include <bux/LR1.h>
// %HEADERS_FOR_HEADER undefined (expanded here otherwise)
// %PRECLASSDECL undefined (expanded here otherwise)

class C_Parser: public bux::LR1::C_Parser
{
public:

    // Ctor
    C_Parser();
// %INCLASSDECL undefined (expanded here otherwise)
};

#endif // ParserH
