// This file is fully generated by running parsergen v1.7.5
// with grammer definition file "grammar.txt"

#pragma once

#include <bux/LR1.h>
// Grammar %HEADERS_FOR_HEADER undefined (expanded here otherwise)
// Grammar %PRECLASSDECL undefined (expanded here otherwise)

class C_Parser: public bux::LR1::C_Parser
{
public:

    // Ctor
    C_Parser();
// Grammar %INCLASSDECL undefined (expanded here otherwise)
};
