// This file is fully generated by running scannergen v1.5.2

// Token-def %HEADERS_FOR_CPP begins
#include "ParserIdDef.h"
// Grammar %HEADERS_FOR_SCANNER_CPP undefined (expanded here otherwise)
// Token-def %HEADERS_FOR_CPP ends

#include "Scanner.h"

namespace {


} // namespace

C_Scanner::C_Scanner(bux::I_Parser &parser):
    bux::C_ScannerImpl<uint8_t,int8_t,bux::C_LexUTF32>(parser)
{
}
