// This file is fully generated by running scannergen v1.5.1

// User-defined %HEADERS_FOR_CPP begins
#include "ParserIdDef.h"
// %HEADERS_FOR_SCANNER_CPP undefined (expanded here otherwise)
// User-defined %HEADERS_FOR_CPP ends

#include "Scanner.h"

namespace {


} // namespace

C_Scanner::C_Scanner(bux::I_Parser &parser):
    bux::C_ScannerImpl<uint8_t,int8_t,bux::C_LexUTF32>(parser)
{
}
