// This file is fully generated by running scannergen
// Read ScannerGen.chm for further info.

// User-defined %HEADERS_FOR_CPP begins
#include "ParserIdDef.h"
// User-defined %HEADERS_FOR_CPP ends

#include "Scanner.h"

namespace {


} // namespace

C_MinScanner::C_MinScanner(bux::I_Parser &parser):
    bux::C_ScannerImpl<uint8_t,int8_t,bux::C_LexUTF32>(parser)
{
}
