// This file is fully generated by running parsergen v1.7.1
// with grammer definition file "grammar.txt"

#pragma once

#include <bux/LexBase.h>    // bux::TOKENGEN_LB

// Token Id Constants
enum
{
    TID_LEX_Bracketed   = bux::TOKENGEN_LB+0,	// $Bracketed
    TID_LEX_Charset     = bux::TOKENGEN_LB+1,	// $Charset
    TID_LEX_Id          = bux::TOKENGEN_LB+2,	// $Id
    TID_LEX_Key         = bux::TOKENGEN_LB+3,	// $Key
    TID_LEX_Num         = bux::TOKENGEN_LB+4,	// $Num
    TID_LEX_Operator    = bux::TOKENGEN_LB+5,	// $Operator
    TID_LEX_Spaces      = bux::TOKENGEN_LB+6,	// $Spaces
    TID_LEX_String      = bux::TOKENGEN_LB+7,	// $String
    TID_KEYWORD_if      = bux::TOKENGEN_LB+8,	// "if"
    TID_KEYWORD_include = bux::TOKENGEN_LB+9,	// "include"
    TID_LITERAL_3e3e    = bux::TOKENGEN_LB+10,	// ">>"
    TID_UB_
};
