// This file is fully generated by running scannergen v1.6.1

// Token-def %HEADERS_FOR_CPP begins
#include "ParserIdDef.h"
// Grammar %HEADERS_FOR_SCANNER_CPP begins
#include "BracketBalance.h"
// Grammar %HEADERS_FOR_SCANNER_CPP ends
// Token-def %HEADERS_FOR_CPP ends

#include "Scanner.h"

namespace {

// ASCII TABLE:
//  0: \x00\x01\x02\x03\x04\x05\x06\a\b\t\n\v\f\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f
// 20:  !\"#$%&\'()*+,-./0123456789:;<=>?
// 40: @ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_
// 60: `abcdefghijklmnopqrstuvwxyz{|}~\x7f
constinit const C_ScannerScanner::C_GotoPair
GOTO_STATE1[3] ={
    {'\x00', 56},
    {'\n', 23},
    {'\v', 56}},
GOTO_STATE2[3] ={
    {'\x00', 89},
    {'*', 90},
    {'+', 89}},
GOTO_STATE3[5] ={
    {'\x00', 89},
    {'*', 90},
    {'+', 89},
    {'/', 33},
    {'0', 89}},
GOTO_STATE4[3] ={
    {'\x00', 91},
    {']', 34},
    {'^', 91}},
GOTO_STATE5[3] ={
    {'\x00', 91},
    {']', 92},
    {'^', 91}},
GOTO_STATE6[6] ={
    {'\t', 6},
    {'\n', std::numeric_limits<int8_t>::max()},
    {'\v', 6},
    {'\x0e', std::numeric_limits<int8_t>::max()},
    {' ', 6},
    {'!', std::numeric_limits<int8_t>::max()}},
GOTO_STATE7[26] ={
    {'\t', 6},
    {'\n', std::numeric_limits<int8_t>::max()},
    {'\v', 6},
    {'\x0e', std::numeric_limits<int8_t>::max()},
    {' ', 6},
    {'!', std::numeric_limits<int8_t>::max()},
    {'\"', 42},
    {'#', std::numeric_limits<int8_t>::max()},
    {'\'', 41},
    {'(', std::numeric_limits<int8_t>::max()},
    {'/', 43},
    {'0', 5},
    {'1', 4},
    {':', std::numeric_limits<int8_t>::max()},
    {'>', 45},
    {'?', std::numeric_limits<int8_t>::max()},
    {'A', 2},
    {'[', 44},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 3},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 1},
    {'i', 40},
    {'j', 1},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE8[5] ={
    {' ', 53},
    {'\'', std::numeric_limits<int8_t>::max()},
    {'(', 53},
    {'\\', 52},
    {']', 53}},
GOTO_STATE9[11] ={
    {' ', 54},
    {'\"', 22},
    {'#', 54},
    {'0', 100},
    {':', 54},
    {'A', 100},
    {'G', 54},
    {'\\', 55},
    {']', 54},
    {'a', 100},
    {'g', 54}},
GOTO_STATE10[11] ={
    {' ', 54},
    {'\"', 22},
    {'#', 54},
    {'0', 101},
    {':', 54},
    {'A', 101},
    {'G', 54},
    {'\\', 55},
    {']', 54},
    {'a', 101},
    {'g', 54}},
GOTO_STATE11[11] ={
    {' ', 54},
    {'\"', 22},
    {'#', 54},
    {'0', 102},
    {':', 54},
    {'A', 102},
    {'G', 54},
    {'\\', 55},
    {']', 54},
    {'a', 102},
    {'g', 54}},
GOTO_STATE12[5] ={
    {' ', 54},
    {'\"', 22},
    {'#', 54},
    {'\\', 55},
    {']', 54}},
GOTO_STATE13[20] ={
    {'\"', 53},
    {'#', std::numeric_limits<int8_t>::max()},
    {'\'', 53},
    {'(', std::numeric_limits<int8_t>::max()},
    {'\\', 53},
    {']', std::numeric_limits<int8_t>::max()},
    {'a', 53},
    {'c', std::numeric_limits<int8_t>::max()},
    {'f', 53},
    {'g', std::numeric_limits<int8_t>::max()},
    {'n', 53},
    {'o', std::numeric_limits<int8_t>::max()},
    {'r', 53},
    {'s', std::numeric_limits<int8_t>::max()},
    {'t', 53},
    {'u', 60},
    {'v', 53},
    {'w', std::numeric_limits<int8_t>::max()},
    {'x', 80},
    {'y', std::numeric_limits<int8_t>::max()}},
GOTO_STATE14[20] ={
    {'\"', 54},
    {'#', std::numeric_limits<int8_t>::max()},
    {'\'', 54},
    {'(', std::numeric_limits<int8_t>::max()},
    {'\\', 54},
    {']', std::numeric_limits<int8_t>::max()},
    {'a', 54},
    {'c', std::numeric_limits<int8_t>::max()},
    {'f', 54},
    {'g', std::numeric_limits<int8_t>::max()},
    {'n', 54},
    {'o', std::numeric_limits<int8_t>::max()},
    {'r', 54},
    {'s', std::numeric_limits<int8_t>::max()},
    {'t', 54},
    {'u', 61},
    {'v', 54},
    {'w', std::numeric_limits<int8_t>::max()},
    {'x', 82},
    {'y', std::numeric_limits<int8_t>::max()}},
GOTO_STATE15[2] ={
    {'\'', 21},
    {'(', std::numeric_limits<int8_t>::max()}},
GOTO_STATE16[8] ={
    {'\'', 21},
    {'(', std::numeric_limits<int8_t>::max()},
    {'0', 53},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 53},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 53},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE17[8] ={
    {'\'', 21},
    {'(', std::numeric_limits<int8_t>::max()},
    {'0', 70},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 70},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 70},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE18[4] ={
    {'*', 57},
    {'+', std::numeric_limits<int8_t>::max()},
    {'/', 56},
    {'0', std::numeric_limits<int8_t>::max()}},
GOTO_STATE19[14] ={
    {'-', 49},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 12},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 10},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 11},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 9},
    {'c', 25},
    {'d', 9},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE20[14] ={
    {'-', 49},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 12},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 10},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 11},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 9},
    {'d', 36},
    {'e', 9},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE21[14] ={
    {'-', 49},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 12},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 10},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 11},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 9},
    {'e', 37},
    {'f', 9},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE22[16] ={
    {'-', 49},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 12},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 10},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 11},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 9},
    {'f', 7},
    {'g', 9},
    {'n', 8},
    {'o', 9},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE23[14] ={
    {'-', 49},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 12},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 10},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 11},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 9},
    {'l', 32},
    {'m', 9},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE24[14] ={
    {'-', 49},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 12},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 10},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 11},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 9},
    {'u', 35},
    {'v', 9},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE25[12] ={
    {'-', 49},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 12},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 10},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 11},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 9},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE26[12] ={
    {'-', 49},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 20},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 15},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 16},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 14},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE27[14] ={
    {'-', 49},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 31},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 30},
    {'G', 15},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 16},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 29},
    {'g', 14},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE28[12] ={
    {'-', 50},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 12},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 10},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 11},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 9},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE29[12] ={
    {'-', 50},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 20},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 15},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 16},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 14},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE30[14] ={
    {'-', 50},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 31},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 30},
    {'G', 15},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 16},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 29},
    {'g', 14},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE31[12] ={
    {'-', 51},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 12},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 10},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 11},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 9},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE32[12] ={
    {'-', 51},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 13},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 15},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 16},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 14},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE33[17] ={
    {'-', 51},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 17},
    {'8', 20},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 15},
    {'X', 19},
    {'Y', 15},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 16},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 14},
    {'x', 18},
    {'y', 14},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE34[13] ={
    {'-', 51},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 17},
    {'8', 20},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 15},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 16},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 14},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE35[12] ={
    {'-', 51},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 20},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 15},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 16},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 14},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE36[14] ={
    {'-', 51},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 31},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 30},
    {'G', 15},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 16},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 29},
    {'g', 14},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE37[8] ={
    {'-', 98},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 69},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 69},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 69},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE38[2] ={
    {'-', 99},
    {'.', std::numeric_limits<int8_t>::max()}},
GOTO_STATE39[10] ={
    {'0', 12},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 10},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 11},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 9},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE40[10] ={
    {'0', 20},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 15},
    {'[', std::numeric_limits<int8_t>::max()},
    {'\\', 46},
    {']', std::numeric_limits<int8_t>::max()},
    {'_', 16},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 14},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE41[2] ={
    {'0', 28},
    {':', std::numeric_limits<int8_t>::max()}},
GOTO_STATE42[6] ={
    {'0', 38},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 38},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 38},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE43[6] ={
    {'0', 39},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 39},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 39},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE44[6] ={
    {'0', 53},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 53},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 53},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE45[6] ={
    {'0', 63},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 63},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 63},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE46[6] ={
    {'0', 64},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 64},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 64},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE47[6] ={
    {'0', 65},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 65},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 65},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE48[6] ={
    {'0', 66},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 66},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 66},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE49[6] ={
    {'0', 67},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 67},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 67},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE50[6] ={
    {'0', 68},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 68},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 68},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE51[6] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE52[6] ={
    {'0', 73},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 73},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 73},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE53[6] ={
    {'0', 74},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 74},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 74},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE54[6] ={
    {'0', 75},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 75},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 75},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE55[6] ={
    {'0', 76},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 76},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 76},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE56[6] ={
    {'0', 77},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 77},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 77},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE57[6] ={
    {'0', 78},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 78},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 78},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE58[6] ={
    {'0', 79},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 79},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 79},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE59[6] ={
    {'0', 81},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 81},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 81},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE60[6] ={
    {'0', 83},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 83},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 83},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE61[6] ={
    {'0', 84},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 84},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 84},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE62[6] ={
    {'0', 85},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 85},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 85},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE63[6] ={
    {'0', 86},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 86},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 86},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE64[6] ={
    {'0', 87},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 87},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 87},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE65[6] ={
    {'0', 88},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 88},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 88},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE66[6] ={
    {'0', 93},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 93},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 93},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE67[6] ={
    {'0', 94},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 94},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 94},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE68[6] ={
    {'0', 95},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 95},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 95},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE69[6] ={
    {'0', 96},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 96},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 96},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE70[6] ={
    {'0', 97},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 97},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 97},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE71[6] ={
    {'0', 103},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 103},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 103},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE72[6] ={
    {'0', 104},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 104},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 104},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE73[6] ={
    {'0', 105},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 105},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 105},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE74[2] ={
    {'>', 24},
    {'?', std::numeric_limits<int8_t>::max()}},
GOTO_STATE75[2] ={
    {'A', 27},
    {'[', std::numeric_limits<int8_t>::max()}},
GOTO_STATE76[2] ={
    {'[', 58},
    {'\\', std::numeric_limits<int8_t>::max()}},
GOTO_STATE77[2] ={
    {'\\', 47},
    {']', std::numeric_limits<int8_t>::max()}},
GOTO_STATE78[2] ={
    {'\\', 48},
    {']', std::numeric_limits<int8_t>::max()}},
GOTO_STATE79[2] ={
    {'a', 26},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE80[2] ={
    {'u', 59},
    {'v', std::numeric_limits<int8_t>::max()}},
GOTO_STATE81[2] ={
    {'u', 62},
    {'v', std::numeric_limits<int8_t>::max()}},
GOTO_STATE82[2] ={
    {'u', 71},
    {'v', std::numeric_limits<int8_t>::max()}};

constinit const C_ScannerScanner::C_StateRec STATES[106] = {
    { GOTO_STATE7,	nullptr	},  // 0
    { GOTO_STATE25,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 1
    { GOTO_STATE28,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 2
    { GOTO_STATE39,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 3
    { GOTO_STATE32,	bux::createDecNum<TID_LEX_Num,bux::C_LexUTF32>	},  // 4
    { GOTO_STATE33,	bux::createDecNum<TID_LEX_Num,bux::C_LexUTF32>	},  // 5
    { GOTO_STATE6,	bux::createNothing<TID_LEX_Spaces,bux::C_LexUTF32>	},  // 6
    { GOTO_STATE25,	bux::createNothing<TID_KEYWORD_if,bux::C_LexUTF32>	},  // 7
    { GOTO_STATE19,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 8
    { GOTO_STATE25,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 9
    { GOTO_STATE28,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 10
    { GOTO_STATE39,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 11
    { GOTO_STATE31,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 12
    { GOTO_STATE32,	bux::createDecNum<TID_LEX_Num,bux::C_LexUTF32>	},  // 13
    { GOTO_STATE26,	bux::createPlainString<TID_LEX_Charset,bux::C_LexUTF32>	},  // 14
    { GOTO_STATE29,	bux::createPlainString<TID_LEX_Charset,bux::C_LexUTF32>	},  // 15
    { GOTO_STATE40,	bux::createPlainString<TID_LEX_Charset,bux::C_LexUTF32>	},  // 16
    { GOTO_STATE34,	bux::createOctNum<TID_LEX_Num,bux::C_LexUTF32>	},  // 17
    { GOTO_STATE27,	bux::createPlainString<TID_LEX_Charset,bux::C_LexUTF32>	},  // 18
    { GOTO_STATE30,	bux::createPlainString<TID_LEX_Charset,bux::C_LexUTF32>	},  // 19
    { GOTO_STATE35,	bux::createPlainString<TID_LEX_Charset,bux::C_LexUTF32>	},  // 20
    { nullptr,	bux::createCharLiteral<TID_LEX_Key,bux::C_LexUTF32>	},  // 21
    { nullptr,	bux::createEscapeString<TID_LEX_String,bux::C_LexUTF32, 1, 1>	},  // 22
    { nullptr,	bux::createNothing<'\n',bux::C_LexUTF32>	},  // 23
    { nullptr,	bux::createNothing<TID_LITERAL_3e3e,bux::C_LexUTF32>	},  // 24
    { GOTO_STATE23,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 25
    { GOTO_STATE40,	bux::createPlainString<TID_LEX_Charset,bux::C_LexUTF32>	},  // 26
    { GOTO_STATE40,	bux::createPlainString<TID_LEX_Charset,bux::C_LexUTF32>	},  // 27
    { GOTO_STATE40,	bux::createPlainString<TID_LEX_Charset,bux::C_LexUTF32>	},  // 28
    { GOTO_STATE27,	bux::createHexNum<TID_LEX_Num,bux::C_LexUTF32>	},  // 29
    { GOTO_STATE30,	bux::createHexNum<TID_LEX_Num,bux::C_LexUTF32>	},  // 30
    { GOTO_STATE36,	bux::createHexNum<TID_LEX_Num,bux::C_LexUTF32>	},  // 31
    { GOTO_STATE24,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 32
    { GOTO_STATE2,	bux::createNothing<TID_LEX_Spaces,bux::C_LexUTF32>	},  // 33
    { GOTO_STATE4,	bux::createPlainString<TID_LEX_Bracketed,bux::C_LexUTF32, 2, 2>	},  // 34
    { GOTO_STATE20,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 35
    { GOTO_STATE21,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 36
    { GOTO_STATE25,	bux::createNothing<TID_KEYWORD_include,bux::C_LexUTF32>	},  // 37
    { GOTO_STATE40,	bux::createPlainString<TID_LEX_Charset,bux::C_LexUTF32>	},  // 38
    { GOTO_STATE40,	bux::createPlainString<TID_LEX_Charset,bux::C_LexUTF32>	},  // 39
    { GOTO_STATE22,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 40
    { GOTO_STATE8,	nullptr	},  // 41
    { GOTO_STATE12,	nullptr	},  // 42
    { GOTO_STATE18,	nullptr	},  // 43
    { GOTO_STATE76,	nullptr	},  // 44
    { GOTO_STATE74,	nullptr	},  // 45
    { GOTO_STATE80,	nullptr	},  // 46
    { GOTO_STATE81,	nullptr	},  // 47
    { GOTO_STATE82,	nullptr	},  // 48
    { GOTO_STATE79,	nullptr	},  // 49
    { GOTO_STATE75,	nullptr	},  // 50
    { GOTO_STATE41,	nullptr	},  // 51
    { GOTO_STATE13,	nullptr	},  // 52
    { GOTO_STATE15,	nullptr	},  // 53
    { GOTO_STATE12,	nullptr	},  // 54
    { GOTO_STATE14,	nullptr	},  // 55
    { GOTO_STATE1,	nullptr	},  // 56
    { GOTO_STATE2,	nullptr	},  // 57
    { GOTO_STATE5,	nullptr	},  // 58
    { GOTO_STATE48,	nullptr	},  // 59
    { GOTO_STATE49,	nullptr	},  // 60
    { GOTO_STATE50,	nullptr	},  // 61
    { GOTO_STATE45,	nullptr	},  // 62
    { GOTO_STATE46,	nullptr	},  // 63
    { GOTO_STATE47,	nullptr	},  // 64
    { GOTO_STATE51,	nullptr	},  // 65
    { GOTO_STATE52,	nullptr	},  // 66
    { GOTO_STATE53,	nullptr	},  // 67
    { GOTO_STATE54,	nullptr	},  // 68
    { GOTO_STATE55,	nullptr	},  // 69
    { GOTO_STATE56,	nullptr	},  // 70
    { GOTO_STATE57,	nullptr	},  // 71
    { GOTO_STATE58,	nullptr	},  // 72
    { GOTO_STATE60,	nullptr	},  // 73
    { GOTO_STATE59,	nullptr	},  // 74
    { GOTO_STATE61,	nullptr	},  // 75
    { GOTO_STATE62,	nullptr	},  // 76
    { GOTO_STATE63,	nullptr	},  // 77
    { GOTO_STATE64,	nullptr	},  // 78
    { GOTO_STATE65,	nullptr	},  // 79
    { GOTO_STATE66,	nullptr	},  // 80
    { GOTO_STATE67,	nullptr	},  // 81
    { GOTO_STATE68,	nullptr	},  // 82
    { GOTO_STATE69,	nullptr	},  // 83
    { GOTO_STATE70,	nullptr	},  // 84
    { GOTO_STATE71,	nullptr	},  // 85
    { GOTO_STATE44,	nullptr	},  // 86
    { GOTO_STATE72,	nullptr	},  // 87
    { GOTO_STATE73,	nullptr	},  // 88
    { GOTO_STATE2,	nullptr	},  // 89
    { GOTO_STATE3,	nullptr	},  // 90
    { GOTO_STATE5,	nullptr	},  // 91
    { GOTO_STATE4,	nullptr	},  // 92
    { GOTO_STATE16,	nullptr	},  // 93
    { GOTO_STATE17,	nullptr	},  // 94
    { GOTO_STATE12,	nullptr	},  // 95
    { GOTO_STATE37,	nullptr	},  // 96
    { GOTO_STATE9,	nullptr	},  // 97
    { GOTO_STATE78,	nullptr	},  // 98
    { GOTO_STATE77,	nullptr	},  // 99
    { GOTO_STATE10,	nullptr	},  // 100
    { GOTO_STATE11,	nullptr	},  // 101
    { GOTO_STATE12,	nullptr	},  // 102
    { GOTO_STATE38,	nullptr	},  // 103
    { GOTO_STATE42,	nullptr	},  // 104
    { GOTO_STATE43,	nullptr	}}; // 105

constinit const uint8_t GOTO_SIZE[106] = {
    26,	// 0
    12,	// 1
    12,	// 2
    10,	// 3
    12,	// 4
    17,	// 5
    6,	// 6
    12,	// 7
    14,	// 8
    12,	// 9
    12,	// 10
    10,	// 11
    12,	// 12
    12,	// 13
    12,	// 14
    12,	// 15
    10,	// 16
    13,	// 17
    14,	// 18
    14,	// 19
    12,	// 20
    0,	// 21
    0,	// 22
    0,	// 23
    0,	// 24
    14,	// 25
    10,	// 26
    10,	// 27
    10,	// 28
    14,	// 29
    14,	// 30
    14,	// 31
    14,	// 32
    3,	// 33
    3,	// 34
    14,	// 35
    14,	// 36
    12,	// 37
    10,	// 38
    10,	// 39
    16,	// 40
    5,	// 41
    5,	// 42
    4,	// 43
    2,	// 44
    2,	// 45
    2,	// 46
    2,	// 47
    2,	// 48
    2,	// 49
    2,	// 50
    2,	// 51
    20,	// 52
    2,	// 53
    5,	// 54
    20,	// 55
    3,	// 56
    3,	// 57
    3,	// 58
    6,	// 59
    6,	// 60
    6,	// 61
    6,	// 62
    6,	// 63
    6,	// 64
    6,	// 65
    6,	// 66
    6,	// 67
    6,	// 68
    6,	// 69
    6,	// 70
    6,	// 71
    6,	// 72
    6,	// 73
    6,	// 74
    6,	// 75
    6,	// 76
    6,	// 77
    6,	// 78
    6,	// 79
    6,	// 80
    6,	// 81
    6,	// 82
    6,	// 83
    6,	// 84
    6,	// 85
    6,	// 86
    6,	// 87
    6,	// 88
    3,	// 89
    5,	// 90
    3,	// 91
    3,	// 92
    8,	// 93
    8,	// 94
    5,	// 95
    8,	// 96
    11,	// 97
    2,	// 98
    2,	// 99
    11,	// 100
    11,	// 101
    5,	// 102
    2,	// 103
    6,	// 104
    6};	// 105

constinit const int8_t FIRST_FITS[2] = {
    33,
    34};

constinit C_ScannerScanner::F_IsFinal *const IS_FINALS[2] = {
    nullptr,
    bux::bracketsMatched};

} // namespace

C_ScannerScanner::C_ScannerScanner(bux::I_Parser &parser):
    bux::C_ScannerImpl<uint8_t,int8_t,bux::C_LexUTF32>(parser)
{
    stateTables(STATES, GOTO_SIZE);
    firstFits(FIRST_FITS, IS_FINALS, 2);
}
