// This file is fully generated by running scannergen v1.6.0

#pragma once

#include <bux/ImplScanner.h>

class C_ScannerScanner: public bux::C_ScannerImpl<uint8_t,int8_t,bux::C_LexUTF32>
{
public:
    C_ScannerScanner(bux::I_Parser &parser);
};
