// This file is fully generated by running parsergen
// with grammer definition file grammar.txt
// Read ParserGen.chm for further info.

#ifndef ParserH
#define ParserH

#include <bux/LR1.h>

// %HEADERS_FOR_HEADER expanded BEGIN
#include "BNFContext.h"     // C_BNFContext
// %HEADERS_FOR_HEADER expanded END

namespace Main {
// %PRECLASSDECL undefined (expanded here otherwise)

class C_BNFParser: public bux::LR1::C_Parser
{
public:

    // Data
    C_BNFContext            m_context;

    // Ctor
    template<class...T_Args>
    C_BNFParser(T_Args&&...args):
        bux::LR1::C_Parser{C_BNFParser::policy()}, m_context{std::forward<T_Args>(args)...} {}

private:

    // Statics
    static const bux::LR1::I_ParserPolicy &policy();
// %INCLASSDECL undefined (expanded here otherwise)
};

} // namespace Main

#endif // ParserH
