// This file is fully generated by running scannergen
// Read ScannerGen.chm for further info.

// User-defined %HEADERS_FOR_CPP begins
#include "ParserIdDef.h"

// %HEADERS_FOR_SCANNER_CPP expanded BEGIN
#include "BracketBalance.h"
// %HEADERS_FOR_SCANNER_CPP expanded END
using namespace Main;
// User-defined %HEADERS_FOR_CPP ends

#include "Scanner.h"

namespace {

// ASCII TABLE:
//  0: \x00\x01\x02\x03\x04\x05\x06\a\b\t\n\v\f\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f
// 20:  !\"#$%&\'()*+,-./0123456789:;<=>?
// 40: @ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_
// 60: `abcdefghijklmnopqrstuvwxyz{|}~\x7f
constinit const C_ParserScanner::C_GotoPair
GOTO_STATE1[3] ={
    {'\x00', 87},
    {'\n', 40},
    {'\v', 87}},
GOTO_STATE2[16] ={
    {'\x00', 87},
    {'\n', 40},
    {'\v', 87},
    {'!', 52},
    {'\"', 88},
    {'#', 52},
    {'\'', 88},
    {'(', 52},
    {'0', 87},
    {':', 52},
    {'A', 87},
    {'[', 52},
    {'_', 87},
    {'`', 52},
    {'a', 87},
    {'{', 52}},
GOTO_STATE3[17] ={
    {'\x00', 89},
    {'!', 54},
    {'\"', 90},
    {'#', 54},
    {'\'', 90},
    {'(', 54},
    {'*', 53},
    {'+', 54},
    {'/', 65},
    {'0', 89},
    {':', 54},
    {'A', 89},
    {'[', 54},
    {'_', 89},
    {'`', 54},
    {'a', 89},
    {'{', 54}},
GOTO_STATE4[16] ={
    {'\x00', 89},
    {'!', 54},
    {'\"', 90},
    {'#', 54},
    {'\'', 90},
    {'(', 54},
    {'*', 53},
    {'+', 54},
    {'0', 89},
    {':', 54},
    {'A', 89},
    {'[', 54},
    {'_', 89},
    {'`', 54},
    {'a', 89},
    {'{', 54}},
GOTO_STATE5[3] ={
    {'\x00', 89},
    {'*', 111},
    {'+', 89}},
GOTO_STATE6[5] ={
    {'\x00', 89},
    {'*', 111},
    {'+', 89},
    {'/', 69},
    {'0', 89}},
GOTO_STATE7[16] ={
    {'\x00', 91},
    {'!', 56},
    {'\"', 92},
    {'#', 56},
    {'\'', 92},
    {'(', 56},
    {'0', 91},
    {':', 56},
    {'A', 91},
    {'[', 56},
    {']', 55},
    {'^', 56},
    {'_', 91},
    {'`', 56},
    {'a', 91},
    {'{', 56}},
GOTO_STATE8[16] ={
    {'\x00', 91},
    {'!', 56},
    {'\"', 92},
    {'#', 56},
    {'\'', 92},
    {'(', 56},
    {'0', 91},
    {':', 56},
    {'A', 91},
    {'[', 56},
    {']', 66},
    {'^', 56},
    {'_', 91},
    {'`', 56},
    {'a', 91},
    {'{', 56}},
GOTO_STATE9[3] ={
    {'\x00', 91},
    {']', 70},
    {'^', 91}},
GOTO_STATE10[3] ={
    {'\x00', 91},
    {']', 112},
    {'^', 91}},
GOTO_STATE11[6] ={
    {'\t', 20},
    {'\n', 40},
    {'\v', 20},
    {'\x0e', std::numeric_limits<int8_t>::max()},
    {' ', 20},
    {'!', std::numeric_limits<int8_t>::max()}},
GOTO_STATE12[39] ={
    {'\t', 20},
    {'\n', std::numeric_limits<int8_t>::max()},
    {'\v', 20},
    {'\r', 21},
    {'\x0e', std::numeric_limits<int8_t>::max()},
    {' ', 20},
    {'!', 73},
    {'\"', 80},
    {'#', 73},
    {'$', 76},
    {'%', 73},
    {'\'', 79},
    {'(', 73},
    {'/', 74},
    {'0', 19},
    {'1', 18},
    {':', 78},
    {';', 73},
    {'<', 77},
    {'=', 73},
    {'A', 72},
    {'[', 75},
    {'\\', 73},
    {'_', 72},
    {'`', 73},
    {'a', 72},
    {'c', 12},
    {'d', 72},
    {'e', 13},
    {'f', 72},
    {'i', 14},
    {'j', 72},
    {'l', 15},
    {'m', 72},
    {'p', 16},
    {'q', 72},
    {'r', 17},
    {'s', 72},
    {'{', 73}},
GOTO_STATE13[6] ={
    {'\t', 20},
    {'\n', std::numeric_limits<int8_t>::max()},
    {'\v', 20},
    {'\x0e', std::numeric_limits<int8_t>::max()},
    {' ', 20},
    {'!', std::numeric_limits<int8_t>::max()}},
GOTO_STATE14[5] ={
    {' ', 83},
    {'\'', std::numeric_limits<int8_t>::max()},
    {'(', 83},
    {'\\', 84},
    {']', 83}},
GOTO_STATE15[5] ={
    {' ', 85},
    {'\"', 39},
    {'#', 85},
    {'\\', 86},
    {']', 85}},
GOTO_STATE16[16] ={
    {'!', 30},
    {'\"', 73},
    {'#', 30},
    {'\'', 73},
    {'(', 30},
    {'*', 34},
    {'+', 30},
    {'/', 33},
    {'0', std::numeric_limits<int8_t>::max()},
    {':', 30},
    {'A', std::numeric_limits<int8_t>::max()},
    {'[', 30},
    {'_', std::numeric_limits<int8_t>::max()},
    {'`', 30},
    {'a', std::numeric_limits<int8_t>::max()},
    {'{', 30}},
GOTO_STATE17[15] ={
    {'!', 30},
    {'\"', 73},
    {'#', 30},
    {'\'', 73},
    {'(', 30},
    {'0', std::numeric_limits<int8_t>::max()},
    {':', 30},
    {'=', 32},
    {'>', 30},
    {'A', std::numeric_limits<int8_t>::max()},
    {'[', 30},
    {'_', std::numeric_limits<int8_t>::max()},
    {'`', 30},
    {'a', std::numeric_limits<int8_t>::max()},
    {'{', 30}},
GOTO_STATE18[15] ={
    {'!', 30},
    {'\"', 73},
    {'#', 30},
    {'\'', 73},
    {'(', 30},
    {'0', std::numeric_limits<int8_t>::max()},
    {':', 30},
    {'>', 31},
    {'?', 30},
    {'A', 81},
    {'[', 30},
    {'_', 81},
    {'`', 30},
    {'a', 81},
    {'{', 30}},
GOTO_STATE19[14] ={
    {'!', 30},
    {'\"', 73},
    {'#', 30},
    {'\'', 73},
    {'(', 30},
    {'0', std::numeric_limits<int8_t>::max()},
    {':', 30},
    {'@', 36},
    {'A', 81},
    {'[', 30},
    {'_', 81},
    {'`', 30},
    {'a', 81},
    {'{', 30}},
GOTO_STATE20[13] ={
    {'!', 30},
    {'\"', 73},
    {'#', 30},
    {'\'', 73},
    {'(', 30},
    {'0', std::numeric_limits<int8_t>::max()},
    {':', 30},
    {'A', 1},
    {'[', 30},
    {'_', 1},
    {'`', 30},
    {'a', 1},
    {'{', 30}},
GOTO_STATE21[13] ={
    {'!', 30},
    {'\"', 73},
    {'#', 30},
    {'\'', 73},
    {'(', 30},
    {'0', std::numeric_limits<int8_t>::max()},
    {':', 30},
    {'A', std::numeric_limits<int8_t>::max()},
    {'[', 30},
    {'_', std::numeric_limits<int8_t>::max()},
    {'`', 30},
    {'a', std::numeric_limits<int8_t>::max()},
    {'{', 30}},
GOTO_STATE22[14] ={
    {'!', 30},
    {'\"', 73},
    {'#', 30},
    {'\'', 73},
    {'(', 30},
    {'0', std::numeric_limits<int8_t>::max()},
    {':', 30},
    {'A', std::numeric_limits<int8_t>::max()},
    {'[', 35},
    {'\\', 30},
    {'_', std::numeric_limits<int8_t>::max()},
    {'`', 30},
    {'a', std::numeric_limits<int8_t>::max()},
    {'{', 30}},
GOTO_STATE23[14] ={
    {'!', 30},
    {'\"', 73},
    {'#', 30},
    {'\'', 73},
    {'(', 30},
    {'0', std::numeric_limits<int8_t>::max()},
    {':', 37},
    {';', 30},
    {'A', std::numeric_limits<int8_t>::max()},
    {'[', 30},
    {'_', std::numeric_limits<int8_t>::max()},
    {'`', 30},
    {'a', std::numeric_limits<int8_t>::max()},
    {'{', 30}},
GOTO_STATE24[22] ={
    {'\"', 83},
    {'#', std::numeric_limits<int8_t>::max()},
    {'\'', 83},
    {'(', std::numeric_limits<int8_t>::max()},
    {'U', 95},
    {'V', std::numeric_limits<int8_t>::max()},
    {'\\', 83},
    {']', std::numeric_limits<int8_t>::max()},
    {'a', 83},
    {'c', std::numeric_limits<int8_t>::max()},
    {'f', 83},
    {'g', std::numeric_limits<int8_t>::max()},
    {'n', 83},
    {'o', std::numeric_limits<int8_t>::max()},
    {'r', 83},
    {'s', std::numeric_limits<int8_t>::max()},
    {'t', 83},
    {'u', 94},
    {'v', 83},
    {'w', std::numeric_limits<int8_t>::max()},
    {'x', 93},
    {'y', std::numeric_limits<int8_t>::max()}},
GOTO_STATE25[22] ={
    {'\"', 85},
    {'#', std::numeric_limits<int8_t>::max()},
    {'\'', 85},
    {'(', std::numeric_limits<int8_t>::max()},
    {'U', 96},
    {'V', std::numeric_limits<int8_t>::max()},
    {'\\', 85},
    {']', std::numeric_limits<int8_t>::max()},
    {'a', 85},
    {'c', std::numeric_limits<int8_t>::max()},
    {'f', 85},
    {'g', std::numeric_limits<int8_t>::max()},
    {'n', 85},
    {'o', std::numeric_limits<int8_t>::max()},
    {'r', 85},
    {'s', std::numeric_limits<int8_t>::max()},
    {'t', 85},
    {'u', 103},
    {'v', 85},
    {'w', std::numeric_limits<int8_t>::max()},
    {'x', 108},
    {'y', std::numeric_limits<int8_t>::max()}},
GOTO_STATE26[2] ={
    {'\'', 38},
    {'(', std::numeric_limits<int8_t>::max()}},
GOTO_STATE27[8] ={
    {'\'', 38},
    {'(', std::numeric_limits<int8_t>::max()},
    {'0', 83},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 83},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 83},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE28[8] ={
    {'0', 1},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 1},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 1},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 1},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE29[2] ={
    {'0', 18},
    {':', std::numeric_limits<int8_t>::max()}},
GOTO_STATE30[6] ={
    {'0', 57},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 57},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 57},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE31[9] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 42},
    {'b', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE32[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'c', 10},
    {'d', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE33[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'c', 47},
    {'d', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE34[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'d', 9},
    {'e', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE35[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'d', 44},
    {'e', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE36[12] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'d', 45},
    {'e', 72},
    {'n', 46},
    {'o', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE37[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'d', 61},
    {'e', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE38[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'d', 71},
    {'e', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE39[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'e', 3},
    {'f', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE40[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'e', 7},
    {'f', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE41[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'e', 27},
    {'f', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE42[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'e', 50},
    {'f', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE43[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'e', 60},
    {'f', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE44[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'e', 67},
    {'f', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE45[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'f', 4},
    {'g', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE46[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'f', 5},
    {'g', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE47[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'f', 6},
    {'g', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE48[12] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'f', 25},
    {'g', 72},
    {'n', 26},
    {'o', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE49[12] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'f', 48},
    {'g', 72},
    {'x', 49},
    {'y', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE50[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'g', 51},
    {'h', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE51[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'h', 64},
    {'i', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE52[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'i', 29},
    {'j', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE53[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'i', 59},
    {'j', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE54[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'i', 63},
    {'j', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE55[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'l', 22},
    {'m', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE56[12] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'l', 23},
    {'m', 72},
    {'n', 24},
    {'o', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE57[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'l', 62},
    {'m', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE58[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'r', 28},
    {'s', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE59[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'s', 2},
    {'t', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE60[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'s', 43},
    {'t', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE61[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'s', 58},
    {'t', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE62[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'t', 8},
    {'u', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE63[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'t', 11},
    {'u', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE64[10] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'u', 68},
    {'v', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE65[8] ={
    {'0', 72},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 72},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 72},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 72},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE66[10] ={
    {'0', 81},
    {':', std::numeric_limits<int8_t>::max()},
    {'>', 41},
    {'?', std::numeric_limits<int8_t>::max()},
    {'A', 81},
    {'[', std::numeric_limits<int8_t>::max()},
    {'_', 81},
    {'`', std::numeric_limits<int8_t>::max()},
    {'a', 81},
    {'{', std::numeric_limits<int8_t>::max()}},
GOTO_STATE67[6] ={
    {'0', 83},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 83},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 83},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE68[6] ={
    {'0', 85},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 85},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 85},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE69[6] ={
    {'0', 94},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 94},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 94},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE70[6] ={
    {'0', 97},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 97},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 97},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE71[6] ={
    {'0', 98},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 98},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 98},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE72[6] ={
    {'0', 99},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 99},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 99},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE73[6] ={
    {'0', 100},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 100},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 100},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE74[6] ={
    {'0', 101},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 101},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 101},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE75[6] ={
    {'0', 102},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 102},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 102},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE76[6] ={
    {'0', 103},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 103},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 103},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE77[6] ={
    {'0', 104},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 104},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 104},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE78[6] ={
    {'0', 105},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 105},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 105},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE79[6] ={
    {'0', 106},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 106},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 106},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE80[6] ={
    {'0', 107},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 107},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 107},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE81[6] ={
    {'0', 109},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 109},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 109},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE82[6] ={
    {'0', 110},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 110},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 110},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE83[6] ={
    {'0', 113},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 113},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 113},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE84[6] ={
    {'0', 114},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 114},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 114},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE85[4] ={
    {'X', 82},
    {'Y', std::numeric_limits<int8_t>::max()},
    {'x', 82},
    {'y', std::numeric_limits<int8_t>::max()}};

constinit const C_ParserScanner::C_StateRec STATES[115] = {
    { GOTO_STATE12,	nullptr	},  // 0
    { GOTO_STATE28,	bux::createPlainString<TID_LEX_LexSymbol,bux::C_LexUTF32, 1, 0>	},  // 1
    { GOTO_STATE65,	bux::createNothing<TID_KEYWORD_class,bux::C_LexUTF32>	},  // 2
    { GOTO_STATE65,	bux::createNothing<TID_KEYWORD_else,bux::C_LexUTF32>	},  // 3
    { GOTO_STATE65,	bux::createNothing<TID_KEYWORD_endif,bux::C_LexUTF32>	},  // 4
    { GOTO_STATE65,	bux::createNothing<TID_KEYWORD_ifdef,bux::C_LexUTF32>	},  // 5
    { GOTO_STATE65,	bux::createNothing<TID_KEYWORD_ifndef,bux::C_LexUTF32>	},  // 6
    { GOTO_STATE65,	bux::createNothing<TID_KEYWORD_include,bux::C_LexUTF32>	},  // 7
    { GOTO_STATE65,	bux::createNothing<TID_KEYWORD_left,bux::C_LexUTF32>	},  // 8
    { GOTO_STATE65,	bux::createNothing<TID_KEYWORD_lexid,bux::C_LexUTF32>	},  // 9
    { GOTO_STATE65,	bux::createNothing<TID_KEYWORD_prec,bux::C_LexUTF32>	},  // 10
    { GOTO_STATE65,	bux::createNothing<TID_KEYWORD_right,bux::C_LexUTF32>	},  // 11
    { GOTO_STATE55,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 12
    { GOTO_STATE56,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 13
    { GOTO_STATE48,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 14
    { GOTO_STATE41,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 15
    { GOTO_STATE58,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 16
    { GOTO_STATE52,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 17
    { GOTO_STATE29,	bux::createDecNum<TID_LEX_Num,bux::C_LexUTF32>	},  // 18
    { GOTO_STATE85,	bux::createDecNum<TID_LEX_Num,bux::C_LexUTF32>	},  // 19
    { GOTO_STATE13,	bux::createNothing<TID_LEX_Spaces,bux::C_LexUTF32>	},  // 20
    { GOTO_STATE11,	bux::createNothing<TID_LEX_Spaces,bux::C_LexUTF32>	},  // 21
    { GOTO_STATE31,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 22
    { GOTO_STATE60,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 23
    { GOTO_STATE35,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 24
    { GOTO_STATE36,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 25
    { GOTO_STATE33,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 26
    { GOTO_STATE49,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 27
    { GOTO_STATE42,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 28
    { GOTO_STATE50,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 29
    { GOTO_STATE21,	bux::createPlainString<TID_LEX_Operator,bux::C_LexUTF32>	},  // 30
    { GOTO_STATE21,	bux::createPlainString<TID_LEX_Nonterminal,bux::C_LexUTF32, 1, 1>	},  // 31
    { GOTO_STATE21,	bux::createNothing<TID_LITERAL_3a3a3d,bux::C_LexUTF32>	},  // 32
    { GOTO_STATE2,	bux::createPlainString<TID_LEX_Operator,bux::C_LexUTF32>	},  // 33
    { GOTO_STATE4,	bux::createPlainString<TID_LEX_Operator,bux::C_LexUTF32>	},  // 34
    { GOTO_STATE7,	bux::createPlainString<TID_LEX_Operator,bux::C_LexUTF32>	},  // 35
    { GOTO_STATE18,	bux::createPlainString<TID_LEX_Operator,bux::C_LexUTF32>	},  // 36
    { GOTO_STATE17,	bux::createNothing<TID_LITERAL_3a3a,bux::C_LexUTF32>	},  // 37
    { nullptr,	bux::createCharLiteral<TID_LEX_Key,bux::C_LexUTF32>	},  // 38
    { nullptr,	bux::createEscapeString<TID_LEX_String,bux::C_LexUTF32, 1, 1>	},  // 39
    { nullptr,	bux::createNothing<'\n',bux::C_LexUTF32>	},  // 40
    { nullptr,	bux::createPlainString<TID_LEX_Nonterminal,bux::C_LexUTF32, 1, 1>	},  // 41
    { GOTO_STATE61,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 42
    { GOTO_STATE39,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 43
    { GOTO_STATE53,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 44
    { GOTO_STATE43,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 45
    { GOTO_STATE37,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 46
    { GOTO_STATE57,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 47
    { GOTO_STATE62,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 48
    { GOTO_STATE54,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 49
    { GOTO_STATE32,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 50
    { GOTO_STATE51,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 51
    { GOTO_STATE2,	bux::createPlainString<TID_LEX_Operator,bux::C_LexUTF32>	},  // 52
    { GOTO_STATE3,	bux::createPlainString<TID_LEX_Operator,bux::C_LexUTF32>	},  // 53
    { GOTO_STATE4,	bux::createPlainString<TID_LEX_Operator,bux::C_LexUTF32>	},  // 54
    { GOTO_STATE8,	bux::createPlainString<TID_LEX_Operator,bux::C_LexUTF32>	},  // 55
    { GOTO_STATE7,	bux::createPlainString<TID_LEX_Operator,bux::C_LexUTF32>	},  // 56
    { GOTO_STATE30,	bux::createHexNum<TID_LEX_Num,bux::C_LexUTF32>	},  // 57
    { GOTO_STATE59,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 58
    { GOTO_STATE45,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 59
    { GOTO_STATE46,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 60
    { GOTO_STATE44,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 61
    { GOTO_STATE64,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 62
    { GOTO_STATE34,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 63
    { GOTO_STATE63,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 64
    { GOTO_STATE4,	bux::createNothing<TID_LEX_Spaces,bux::C_LexUTF32>	},  // 65
    { GOTO_STATE8,	bux::createPlainString<TID_LEX_Bracketed,bux::C_LexUTF32, 2, 2>	},  // 66
    { GOTO_STATE47,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 67
    { GOTO_STATE38,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 68
    { GOTO_STATE5,	bux::createNothing<TID_LEX_Spaces,bux::C_LexUTF32>	},  // 69
    { GOTO_STATE9,	bux::createPlainString<TID_LEX_Bracketed,bux::C_LexUTF32, 2, 2>	},  // 70
    { GOTO_STATE40,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 71
    { GOTO_STATE65,	bux::createPlainString<TID_LEX_Id,bux::C_LexUTF32>	},  // 72
    { GOTO_STATE21,	nullptr	},  // 73
    { GOTO_STATE16,	nullptr	},  // 74
    { GOTO_STATE22,	nullptr	},  // 75
    { GOTO_STATE20,	nullptr	},  // 76
    { GOTO_STATE19,	nullptr	},  // 77
    { GOTO_STATE23,	nullptr	},  // 78
    { GOTO_STATE14,	nullptr	},  // 79
    { GOTO_STATE15,	nullptr	},  // 80
    { GOTO_STATE66,	nullptr	},  // 81
    { GOTO_STATE30,	nullptr	},  // 82
    { GOTO_STATE26,	nullptr	},  // 83
    { GOTO_STATE24,	nullptr	},  // 84
    { GOTO_STATE15,	nullptr	},  // 85
    { GOTO_STATE25,	nullptr	},  // 86
    { GOTO_STATE1,	nullptr	},  // 87
    { GOTO_STATE2,	nullptr	},  // 88
    { GOTO_STATE5,	nullptr	},  // 89
    { GOTO_STATE4,	nullptr	},  // 90
    { GOTO_STATE10,	nullptr	},  // 91
    { GOTO_STATE7,	nullptr	},  // 92
    { GOTO_STATE83,	nullptr	},  // 93
    { GOTO_STATE77,	nullptr	},  // 94
    { GOTO_STATE70,	nullptr	},  // 95
    { GOTO_STATE71,	nullptr	},  // 96
    { GOTO_STATE72,	nullptr	},  // 97
    { GOTO_STATE73,	nullptr	},  // 98
    { GOTO_STATE74,	nullptr	},  // 99
    { GOTO_STATE75,	nullptr	},  // 100
    { GOTO_STATE69,	nullptr	},  // 101
    { GOTO_STATE76,	nullptr	},  // 102
    { GOTO_STATE78,	nullptr	},  // 103
    { GOTO_STATE79,	nullptr	},  // 104
    { GOTO_STATE80,	nullptr	},  // 105
    { GOTO_STATE81,	nullptr	},  // 106
    { GOTO_STATE82,	nullptr	},  // 107
    { GOTO_STATE84,	nullptr	},  // 108
    { GOTO_STATE67,	nullptr	},  // 109
    { GOTO_STATE68,	nullptr	},  // 110
    { GOTO_STATE6,	nullptr	},  // 111
    { GOTO_STATE9,	nullptr	},  // 112
    { GOTO_STATE27,	nullptr	},  // 113
    { GOTO_STATE15,	nullptr	}}; // 114

constinit const uint8_t GOTO_SIZE[115] = {
    39,	// 0
    8,	// 1
    8,	// 2
    8,	// 3
    8,	// 4
    8,	// 5
    8,	// 6
    8,	// 7
    8,	// 8
    8,	// 9
    8,	// 10
    8,	// 11
    10,	// 12
    12,	// 13
    12,	// 14
    10,	// 15
    10,	// 16
    10,	// 17
    2,	// 18
    4,	// 19
    6,	// 20
    6,	// 21
    9,	// 22
    10,	// 23
    10,	// 24
    12,	// 25
    10,	// 26
    12,	// 27
    10,	// 28
    10,	// 29
    13,	// 30
    13,	// 31
    13,	// 32
    16,	// 33
    16,	// 34
    16,	// 35
    15,	// 36
    15,	// 37
    0,	// 38
    0,	// 39
    0,	// 40
    0,	// 41
    10,	// 42
    10,	// 43
    10,	// 44
    10,	// 45
    10,	// 46
    10,	// 47
    10,	// 48
    10,	// 49
    10,	// 50
    10,	// 51
    16,	// 52
    17,	// 53
    16,	// 54
    16,	// 55
    16,	// 56
    6,	// 57
    10,	// 58
    10,	// 59
    10,	// 60
    10,	// 61
    10,	// 62
    10,	// 63
    10,	// 64
    16,	// 65
    16,	// 66
    10,	// 67
    10,	// 68
    3,	// 69
    3,	// 70
    10,	// 71
    8,	// 72
    13,	// 73
    16,	// 74
    14,	// 75
    13,	// 76
    14,	// 77
    14,	// 78
    5,	// 79
    5,	// 80
    10,	// 81
    6,	// 82
    2,	// 83
    22,	// 84
    5,	// 85
    22,	// 86
    3,	// 87
    16,	// 88
    3,	// 89
    16,	// 90
    3,	// 91
    16,	// 92
    6,	// 93
    6,	// 94
    6,	// 95
    6,	// 96
    6,	// 97
    6,	// 98
    6,	// 99
    6,	// 100
    6,	// 101
    6,	// 102
    6,	// 103
    6,	// 104
    6,	// 105
    6,	// 106
    6,	// 107
    6,	// 108
    6,	// 109
    6,	// 110
    5,	// 111
    3,	// 112
    8,	// 113
    5};	// 114

const int8_t FIRST_FITS[4] = {
    65,
    66,
    69,
    70};

C_ParserScanner::F_IsFinal *const IS_FINALS[4] = {
    nullptr,
    bux::bracketsMatched,
    nullptr,
    bux::bracketsMatched};

} // namespace

C_ParserScanner::C_ParserScanner(bux::I_Parser &parser):
    bux::C_ScannerImpl<uint8_t,int8_t,bux::C_LexUTF32>(parser)
{
    stateTables(STATES, GOTO_SIZE);
    firstFits(FIRST_FITS, IS_FINALS, 4);
}
